modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"
issueTrackerURL="https://discord.gg/ZYS2Y7Nu7f"
[[mods]]
modId="projecta"
version="Dev Build"
displayName="Project A"
updateJSONURL="https://discord.gg/ZYS2Y7Nu7f"
displayURL="https://discord.gg/ZYS2Y7Nu7f"
#logoFile="examplemod.png"
credits="Placeholder Credits"
authors="LOSERs Group Games"
description='''
Placeholder Description
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
